[package]
name = "meos-rs"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "meos"

[dependencies]
meos-sys = { path = "meos-sys" }

[dev-dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
